name: Deploy to EC2 via SSH

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # shallow clone; remote reset handles sync

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          DOT_ENV_CONTENT: ${{ secrets.DOT_ENV_FILE }}
        run: |
          echo "Connecting to ${USER}@${HOST}"
          ssh ${USER}@${HOST} << 'EOF'
            set -e
            cd ${PROJECT_PATH}
            echo "Current directory: $(pwd)"

            echo "Cleaning up old Docker data…"
            sudo docker system prune -af
            sudo docker volume prune -f

            echo "Resetting code to origin/master..."
            git fetch origin master
            git reset --hard origin/master
            git clean -fd

            echo "Writing .env file..."
            printf "%s\n" "${DOT_ENV_CONTENT}" > .env
            chmod 600 .env

            echo "Stopping existing services…"
            sudo docker-compose down --remove-orphans

            echo "Building and starting services…"
            sudo docker-compose up --build -d

            echo "Deployment finished!"
          EOF
